{
 "title": "Cluster",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "datastore",
    "query": {
     "query": "label_values(one_datastore_available{cluster=~\"$cluster\"},datastore)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Cluster", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(one_vm_state{cluster=\"$cluster\",state=\"ACTIVE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Running Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(one_host_state{cluster=\"$cluster\",state=\"MONITORED\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Host State",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
   "targets": [
    {
     "expr": "one_host_state{cluster=~\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total CPU * 100",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "one_cluster_maxcpu{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated CPU * 100",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "one_cluster_cpuusage{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((one_cluster_cpuusage{cluster=~\"$cluster\"} * 100) / (one_cluster_maxcpu{cluster=~\"$cluster\"}))"
    }
   ]
  },
  {
   "title": "Offline VMs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(one_vm_state{cluster=\"$cluster\",state!=\"ACTIVE\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Offline Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(one_host_state{cluster=\"$cluster\",state!=\"MONITORED\"}) OR on() vector(0)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "one_cluster_maxmem{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "one_cluster_memusage{cluster=\"$cluster\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Allocated RAM ",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum((one_cluster_memusage{cluster=\"$cluster\"} * 100) / one_cluster_maxmem{cluster=\"$cluster\"})"
    }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "targets": [
    {
     "expr": "one_host_memusage{cluster=\"$cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Allocated CPUs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "one_host_cpuusage{cluster=\"$cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "VMs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "one_host_runningvms{cluster=\"$cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  { "title": "Datastore", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Datastore \"$datastore\" Status",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 26 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "one_datastore_state{datastore=~\"$datastore\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Datastore \"$datastore\" Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 6, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "one_datastore_totalmb{datastore=~\"$datastore\"}",
     "legendFormat": "total"
    },
    {
     "expr": "one_datastore_freemb{datastore=~\"$datastore\"}",
     "legendFormat": "free"
    },
    {
     "expr": "one_datastore_usedmb{datastore=~\"$datastore\"}",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "Datastore State",
   "type": "table",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 26 },
   "targets": [
    { "expr": "one_datastore_state", "legendFormat": "__auto" }
   ]
  }
 ]
}