{
 "title": "Nodes",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "cluster", "query": { "query": "label_values(cluster)" } },
   {
    "name": "node",
    "query": {
     "query": "label_values(one_host_state,host)"
    }
   }
  ]
 },
 "panels": [
  { "title": "$node", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "node" },
  {
   "title": "Allocated VCPUs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "one_host_cpuusage{cluster=\"$cluster\",host=~\"$node\"}",
     "legendFormat": "used"
    },
    {
     "expr": "one_host_maxcpu{cluster=\"$cluster\", host=~\"$node\"}",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "VMs States",
   "type": "table",
   "gridPos": { "h": 11, "w": 8, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "one_vm_state{host=~\"$node.*\"} + on(vm) group_left(lcm_state) one_vm_lcmstate{host=~\"$node.*\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by (cpu) (irate(node_cpu_seconds_total{instance=~\"$node\", mode!~\"idle\"}[1m])) * 100",
     "legendFormat": "cpu {{cpu}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node.*\"} - node_memory_MemFree_bytes{instance=~\"$node.*\"} - (node_memory_Cached_bytes{instance=~\"$node.*\"} + node_memory_Buffers_bytes{instance=~\"$node.*\"})",
     "legendFormat": "used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node.*\"} + node_memory_Buffers_bytes{instance=~\"$node.*\"}",
     "legendFormat": "cache + buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node.*\"}",
     "legendFormat": "free"
    }
   ]
  },
  {
   "title": "Allocated RAM",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "kbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "one_host_memusage{host=~\"$node\"}",
     "legendFormat": "used"
    },
    {
     "expr": "one_host_maxmem{host=~\"$node\"}",
     "legendFormat": "available"
    }
   ]
  },
  {
   "title": "Running VMs",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "one_host_runningvms{cluster=\"$cluster\", host=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "one_host_state{cluster=\"$cluster\",host=~\"$node\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}